/**
 * The learning-material catalog — the single source of truth for both the
 * landing-page listing and the Starlight sidebar.
 *
 * Adding a material: create `src/content/docs/<slug>/` with an `index.md`,
 * add a `sections` entry per subdirectory, then append the material here.
 * Nothing else needs to change — `astro.config.mjs` and `src/pages`-free
 * routing pick it up automatically.
 */

export interface MaterialSection {
  /** Label shown as the sidebar group heading. */
  label: string;
  /** Directory under `src/content/docs/<slug>/`, autogenerated into the sidebar. */
  directory: string;
}

export interface Material {
  /** URL segment and content directory name, e.g. `spring-boot-ticketing`. */
  slug: string;
  /** Display title, used on the card and as the sidebar group label. */
  title: string;
  /** One-line summary for the catalog card. */
  description: string;
  /** Longer pitch shown on the material's own landing section. */
  tagline: string;
  level: 'Beginner' | 'Intermediate' | 'Advanced';
  /** Rough size, e.g. "26 steps". Shown on the card. */
  size: string;
  tags: string[];
  status: 'available' | 'draft' | 'planned';
  /** Page a reader should land on from the catalog card. */
  entry: string;
  /** Extra top-level sidebar links rendered above the section groups. */
  links: { label: string; slug: string }[];
  sections: MaterialSection[];
}

export const materials: Material[] = [
  {
    slug: 'spring-boot-ticketing',
    title: 'Spring Boot — Event Ticketing Marketplace',
    description:
      'Go from "I know Java, new to Spring" to a production-grade backend and fullstack app, built around one real domain: an event ticketing marketplace.',
    tagline:
      'Twenty-six steps, one real domain. Concurrency, consistency, and distributed-systems reasoning you cannot fake with a todo app.',
    level: 'Intermediate',
    size: '26 steps',
    tags: ['Java 21', 'Spring Boot 3.5', 'PostgreSQL', 'React', 'AI-assisted'],
    status: 'available',
    entry: 'spring-boot-ticketing',
    links: [{ label: 'Getting Started', slug: 'spring-boot-ticketing' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'fastapi-support-assistant',
    title: 'FastAPI — Grounded Support Assistant',
    description:
      'Go from "I know Python, new to FastAPI" to an AI feature you can prove works — grounded answers, real citations, refusal when the documents do not say, and an evaluation report to show for it.',
    tagline:
      'Eighteen steps, one real domain. Retrieval, refusal and evaluation — the half of an AI product that separates a demo from something a clinic will use.',
    level: 'Intermediate',
    size: '18 steps',
    tags: ['Python 3.13', 'FastAPI', 'PostgreSQL + pgvector', 'Claude API', 'Evaluation'],
    status: 'available',
    entry: 'fastapi-support-assistant',
    links: [{ label: 'Getting Started', slug: 'fastapi-support-assistant' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'laravel-spreadsheet-migration',
    title: 'Laravel — Off the Spreadsheet Back Office',
    description:
      'Go from "I can build a Laravel app" to the job small businesses actually hire for: moving a living business off its spreadsheets — discovery, messy import, entity resolution, reconciliation and cutover — without stopping it for a day.',
    tagline:
      'Sixteen steps, one real domain. The requirements are a spreadsheet nobody has written down, and the client can check your numbers.',
    level: 'Intermediate',
    size: '16 steps',
    tags: ['PHP 8.5', 'Laravel 13', 'Filament', 'PostgreSQL', 'Spreadsheet import'],
    status: 'available',
    entry: 'laravel-spreadsheet-migration',
    links: [{ label: 'Getting Started', slug: 'laravel-spreadsheet-migration' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
  {
    slug: 'n8n-ai-operations',
    title: 'n8n — AI Operations Automation',
    description:
      'Go from "I can write code" to the work businesses pay a retainer for: AI steps inside a real daily process, with replay, human sign-off, a confidentiality answer a solicitor accepts, and a cost dashboard the client reads.',
    tagline:
      'Sixteen steps, three real clients. A step whose output you cannot predict, inside a process that needs guarantees — which is the part no no-code build has.',
    level: 'Intermediate',
    size: '16 steps',
    tags: ['n8n', 'TypeScript 5.9', 'PostgreSQL', 'Claude API', 'Self-hosted', 'Integration'],
    status: 'available',
    entry: 'n8n-ai-operations',
    links: [{ label: 'Getting Started', slug: 'n8n-ai-operations' }],
    sections: [
      { label: 'Setup', directory: 'setup' },
      { label: 'Roadmap', directory: 'roadmap' },
      { label: 'Reference', directory: 'reference' },
    ],
  },
];

export const publishedMaterials = materials.filter((m) => m.status !== 'planned');

/** Find the material that owns a given page pathname, e.g. `/spring-boot-ticketing/setup/`. */
export function materialForPathname(pathname: string, base = '/'): Material | undefined {
  const withoutBase = pathname.slice(base.replace(/\/$/, '').length);
  const slug = withoutBase.split('/').filter(Boolean)[0];
  return materials.find((m) => m.slug === slug);
}
